import {createDocument,createEngine,validateDocument,objectBounds,LIMITS} from './engine.js';
import {encodeSnapshot,decodeSnapshot,snapshotHash,shareURL,forkDocument,resolveSource,prepareQuoteCommand} from './share.js';
import {installWebMCP} from './webmcp.js';
import {createStorage} from './storage.js';
import {installCommunication} from './communication.js';
import {installStory} from './story.js';

const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
const engine=createEngine(createDocument({title:'함께 그리는 첫 장',author:'나'}));
let doc=engine.getDocument(),storage,adapter,selection=[],tool='select',viewport={x:0,y:0,zoom:1};
let stroke='#7160d8',fill='#e9e3ff',filled=false,width=3,fontSize=24,gesture=null,space=false,textTarget=null;
let saveTimer,toastTimer,persistQueue=Promise.resolve(),demoController=null,loading=true,routeVersion=0,hasDocument=false;
let committedURL=location.pathname+location.search;
let communication,story;
const colors=['#7160d8','#343141','#e996a5','#e3b46e','#8fb894','#8eafd6','#b997cf','#8a898f','#f3d6de','#f3e2be','#d6e8d3','#d7e3f3'];
const round=n=>Math.round(n*100)/100;
function svg(tag,attrs={},text){const node=document.createElementNS(NS,tag);for(const [key,value]of Object.entries(attrs))node.setAttribute(key,String(value));if(text!==undefined)node.textContent=text;return node;}
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,error?7000:3500);}
function handleError(error){toast(error?.message||String(error),true);}
function check(result){if(!result?.ok){const e=new Error(result?.error?.message||'작업을 완료하지 못했어요.');e.code=result?.error?.code;throw e;}return result;}
function writable(){if(engine.isReadOnly()){toast('원본을 포크하면 내 보드에서 수정할 수 있어요.');return false;}return !loading;}
function act(command){if(!writable())return;try{return check(engine.execute(command,{actor:'human'}));}catch(e){handleError(e);}}
function busyButton(id,task){const button=$(id);button.addEventListener('click',async()=>{if(button.disabled)return;button.disabled=true;try{await task();}catch(e){handleError(e);}finally{button.disabled=false;}});}

function drawObject(o,{interactive=false}={}){
  const group=svg('g',interactive?{'data-object-id':o.id}:{});
  let shape;
  const common={stroke:o.stroke,fill:o.fill==='none'?'none':o.fill,'stroke-width':o.strokeWidth,'stroke-linecap':'round','stroke-linejoin':'round'};
  if(o.type==='path'){
    const p=o.points;
    if(p.length===1)shape=svg('circle',{cx:p[0][0],cy:p[0][1],r:Math.max(.5,o.strokeWidth/2),fill:o.stroke,stroke:'none'});
    else shape=svg('path',{d:p.map(([x,y],i)=>`${i?'L':'M'}${x} ${y}`).join(' '),...common,fill:'none'});
  }else if(o.type==='rect')shape=svg('rect',{x:o.x,y:o.y,width:o.width,height:o.height,rx:Math.min(12,o.width/8,o.height/8),...common});
  else if(o.type==='ellipse')shape=svg('ellipse',{cx:o.x+o.width/2,cy:o.y+o.height/2,rx:o.width/2,ry:o.height/2,...common});
  else if(o.type==='line')shape=svg('line',{x1:o.x,y1:o.y,x2:o.x+o.width,y2:o.y+o.height,...common});
  else if(o.type==='note'||o.type==='bubble'){
    const background=o.type==='note'?svg('rect',{x:o.x,y:o.y,width:o.width,height:o.height,rx:8,fill:o.fill,stroke:o.stroke,'stroke-width':o.strokeWidth}):svg('path',{d:`M${o.x+12} ${o.y} H${o.x+o.width-12} Q${o.x+o.width} ${o.y} ${o.x+o.width} ${o.y+12} V${o.y+o.height-32} Q${o.x+o.width} ${o.y+o.height-20} ${o.x+o.width-12} ${o.y+o.height-20} H${o.x+48} L${o.x+22} ${o.y+o.height} V${o.y+o.height-20} H${o.x+12} Q${o.x} ${o.y+o.height-20} ${o.x} ${o.y+o.height-32} V${o.y+12} Q${o.x} ${o.y} ${o.x+12} ${o.y} Z`,fill:o.fill,stroke:o.stroke,'stroke-width':o.strokeWidth});
    group.append(background);shape=svg('text',{x:o.x+18,y:o.y+20+o.fontSize,'font-family':'Inter, Pretendard, sans-serif','font-size':o.fontSize,fill:o.stroke,stroke:'none'});
    const max=Math.max(1,(o.width-36)/o.fontSize),lines=[];for(const line of o.text.split('\n')){let current='',length=0;for(const ch of line){const step=ch.charCodeAt(0)>255?1:.6;if(length+step>max&&current){lines.push(current);current='';length=0;}current+=ch;length+=step;}lines.push(current);}
    const limit=Math.max(1,Math.floor((o.height-(o.type==='bubble'?48:28))/(o.fontSize*1.3)));
    lines.slice(0,limit).forEach((line,i)=>shape.append(svg('tspan',{x:o.x+18,dy:i?o.fontSize*1.3:0},i===limit-1&&lines.length>limit?`${line.slice(0,-1)}…`:line||' ')));
  }
  else if(o.type==='text'){
    shape=svg('text',{x:o.x,y:o.y+o.fontSize,'font-family':'Inter, Pretendard, "Noto Sans KR", sans-serif','font-size':o.fontSize,fill:o.stroke,stroke:'none','font-weight':o.fontSize>=32?600:450});
    o.text.split('\n').forEach((line,i)=>shape.append(svg('tspan',{x:o.x,dy:i?o.fontSize*1.3:0},line||' ')));
  }
  if(o.rotation){const b=objectBounds({...o,rotation:0});group.setAttribute('transform',`rotate(${o.rotation} ${b.x+b.width/2} ${b.y+b.height/2})`);}
  if(shape){if(interactive)shape.style.pointerEvents='visiblePainted';group.append(shape);}
  return group;
}
function bounds(objects=doc.objects){if(!objects.length)return{x:0,y:0,width:800,height:560};let x=Infinity,y=Infinity,right=-Infinity,bottom=-Infinity;for(const o of objects){const b=objectBounds(o),pad=Math.max(o.strokeWidth/2,2);x=Math.min(x,b.x-pad);y=Math.min(y,b.y-pad);right=Math.max(right,b.x+b.width+pad);bottom=Math.max(bottom,b.y+b.height+pad);}return{x,y,width:Math.max(1,right-x),height:Math.max(1,bottom-y)};}
function setViewport(next){if(![next.x,next.y,next.zoom].every(Number.isFinite))throw new Error('화면 위치가 올바르지 않아요.');viewport={x:Math.max(-100000,Math.min(100000,next.x)),y:Math.max(-100000,Math.min(100000,next.y)),zoom:Math.max(.1,Math.min(4,next.zoom))};$('world').setAttribute('transform',`translate(${viewport.x} ${viewport.y}) scale(${viewport.zoom})`);$('canvas-area').style.backgroundSize=`${24*viewport.zoom}px ${24*viewport.zoom}px`;$('canvas-area').style.backgroundPosition=`${viewport.x}px ${viewport.y}px`;$('zoom-value').textContent=`${Math.round(viewport.zoom*100)}%`;renderSelection();}
function fitView(){const b=bounds(),r=$('board').getBoundingClientRect(),padding=95;const zoom=Math.max(.1,Math.min(1.25,(r.width-padding)/b.width,(r.height-padding)/b.height));setViewport({x:(r.width-b.width*zoom)/2-b.x*zoom,y:(r.height-b.height*zoom)/2-b.y*zoom+8,zoom});}
function zoomAt(factor,sx,sy){const r=$('board').getBoundingClientRect();sx??=r.width/2;sy??=r.height/2;const z=Math.max(.1,Math.min(4,viewport.zoom*factor));setViewport({zoom:z,x:sx-(sx-viewport.x)*z/viewport.zoom,y:sy-(sy-viewport.y)*z/viewport.zoom});}
function worldPoint(event){const r=$('board').getBoundingClientRect();return{x:round((event.clientX-r.left-viewport.x)/viewport.zoom),y:round((event.clientY-r.top-viewport.y)/viewport.zoom)};}
function setSelection(ids){const known=new Set(doc.objects.map(o=>o.id));selection=[...new Set(ids)].filter(id=>known.has(id));renderSelection();}
function renderSelection(){const layer=$('selection');layer.replaceChildren();for(const id of selection){const o=doc.objects.find(o=>o.id===id);if(!o)continue;const b=objectBounds(o),p=5/viewport.zoom;layer.append(svg('rect',{x:b.x-p,y:b.y-p,width:Math.max(b.width,1)+p*2,height:Math.max(b.height,1)+p*2,fill:'none',stroke:'#9b80e0','stroke-width':1/viewport.zoom,'stroke-dasharray':`${4/viewport.zoom} ${3/viewport.zoom}`,rx:3/viewport.zoom,'pointer-events':'none'}));}const exists=selection.length>0;$('selection-toolbar').hidden=!exists;$('selection-count').textContent=`${selection.length}개 선택`;$('duplicate-selection').disabled=engine.isReadOnly();$('delete-selection').disabled=engine.isReadOnly();}
function renderAgent(){const a=doc.agent,layer=$('agent-cursor');layer.replaceChildren();layer.setAttribute('transform',`translate(${a.x} ${a.y})`);const scale=1/Math.max(viewport.zoom,.5),g=svg('g',{transform:`scale(${scale})`,'pointer-events':'none'});g.append(svg('circle',{r:23,class:'agent-glow'}));g.append(svg('path',{d:'M 18 0 L -10 -12 L -5 0 L -10 12 Z',class:'agent-body',transform:`rotate(${a.heading})`}));g.append(svg('text',{x:-13,y:39,class:'agent-label'},a.penDown?'보라 · 그리고 있어요':'보라'));layer.append(g);$('agent-position').textContent=`x ${Math.round(a.x)} · y ${Math.round(a.y)}`;$('agent-pen-toggle').setAttribute('aria-pressed',String(a.penDown));}
function render(){doc=engine.getDocument();const frag=document.createDocumentFragment();doc.objects.forEach(o=>frag.append(drawObject(o,{interactive:true})));$('objects').replaceChildren(frag);selection=selection.filter(id=>doc.objects.some(o=>o.id===id));renderSelection();renderAgent();$('object-count').textContent=`${doc.objects.length}개의 오브젝트`;$('undo').disabled=!engine.canUndo();$('redo').disabled=!engine.canRedo();if(document.activeElement!==$('board-title'))$('board-title').value=doc.title;if(document.activeElement!==$('author'))$('author').value=doc.author;$('board-title').readOnly=engine.isReadOnly();$('author').readOnly=engine.isReadOnly();$('source-banner').hidden=!engine.isReadOnly();$('document-mode').textContent=engine.isReadOnly()?'QUOTED ORIGINAL':'MY CANVAS';document.body.classList.toggle('read-only',engine.isReadOnly());document.title=`${doc.title} · Grimpan`;}
function renderSources(){const list=$('source-list');list.replaceChildren();if(!doc.provenance.length){const empty=document.createElement('div');empty.className='source-empty';empty.textContent='이 그림은 여기서 시작됐어요.\n포크한 그림의 원본은 이곳에 남아요.';list.append(empty);return;}doc.provenance.forEach((entry,i)=>{const item=document.createElement('article');item.className='source-item';const label=document.createElement('span');label.textContent=i===0?'DIRECT QUOTE · 직접 인용':'EARLIER SOURCE · 이전 원본';const h=document.createElement('h3');h.textContent=entry.title;const p=document.createElement('p');p.textContent=`${entry.author} · ${new Date(entry.createdAt).toLocaleDateString('ko-KR')}`;const hash=document.createElement('code');hash.textContent=`SHA-256 ${entry.sourceHash.slice(0,20)}…`;const button=document.createElement('button');button.textContent='원본 열기 ↗';button.disabled=!entry.snapshot;button.addEventListener('click',async()=>{try{const original=resolveSource(doc,entry.sourceHash);await openSource(original);switchPanel('source');toast('인용한 원본을 열었어요.');}catch(e){handleError(e);}});const compare=document.createElement('button');compare.textContent='나란히 비교';compare.disabled=!entry.snapshot;compare.onclick=()=>{try{story?.compareWith(resolveSource(doc,entry.sourceHash));}catch(e){handleError(e);}};const buttons=document.createElement('div');buttons.className='source-buttons';buttons.append(button,compare);item.append(label,h,p,hash,buttons);list.append(item);});}
function switchPanel(name){document.querySelectorAll('[data-panel]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.panel===name)));document.querySelectorAll('.side-panel .panel-body').forEach(panel=>panel.hidden=panel.id!==`panel-${name}`);if(name==='source')renderSources();}
function chooseTool(name){tool=name;$('canvas-area').dataset.tool=name;document.querySelectorAll('[data-tool]').forEach(button=>{const active=button.dataset.tool===name;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});const hints={select:'드래그로 이동 · Shift로 여러 개 선택 · Space로 화면 이동',pen:'드래그해서 선 그리기 · Ctrl/⌘ Z로 되돌리기',rect:'드래그해서 사각형 · Shift로 정사각형',ellipse:'드래그해서 원 · Shift로 정원',line:'드래그해서 선 · Shift로 수평 / 수직',text:'보드를 클릭해서 이야기 적기 · 글자를 더블클릭하면 수정',eraser:'클릭해서 객체 하나 지우기 · Ctrl/⌘ Z로 되돌리기',hand:'드래그로 화면 이동 · 휠로 확대 / 축소',note:'보드를 클릭해서 색깔 메모를 붙여요',bubble:'말풍선으로 그림에 이야기를 더해요'};$('tool-hint').textContent=hints[name];}
function previewShape(o){$('preview').replaceChildren(drawObject({...o,id:'preview',rotation:0}));}
function translated(o,dx,dy){return o.type==='path'?{...o,points:o.points.map(([x,y])=>[x+dx,y+dy])}:{...o,x:o.x+dx,y:o.y+dy};}
function shapeFromGesture(g,p,shift=false){let dx=p.x-g.start.x,dy=p.y-g.start.y;if(shift&&g.tool!=='line'){const n=Math.max(Math.abs(dx),Math.abs(dy));dx=Math.sign(dx||1)*n;dy=Math.sign(dy||1)*n;}if(shift&&g.tool==='line'){if(Math.abs(dx)>Math.abs(dy))dy=0;else dx=0;}return{type:g.tool,x:g.tool==='line'?g.start.x:Math.min(g.start.x,g.start.x+dx),y:g.tool==='line'?g.start.y:Math.min(g.start.y,g.start.y+dy),width:g.tool==='line'?dx:Math.abs(dx),height:g.tool==='line'?dy:Math.abs(dy),stroke,fill:filled?fill:'transparent',strokeWidth:width};}
function hitObject(event,p){const id=event.target.closest?.('[data-object-id]')?.dataset.objectId;if(id)return id;return [...doc.objects].reverse().find(o=>{const b=objectBounds(o),pad=4/viewport.zoom;return p.x>=b.x-pad&&p.x<=b.x+b.width+pad&&p.y>=b.y-pad&&p.y<=b.y+b.height+pad;})?.id;}
function cancelGesture(){gesture=null;$('preview').replaceChildren();$('canvas-area').classList.remove('panning');$('objects').querySelectorAll('[opacity]').forEach(n=>n.removeAttribute('opacity'));}

$('board').addEventListener('pointerdown',e=>{
  if(e.button!==0&&e.button!==1)return;if(gesture)return;const p=worldPoint(e);$('board').focus({preventScroll:true});
  if(tool==='hand'||space||e.button===1){gesture={kind:'pan',start:{x:e.clientX,y:e.clientY},viewport:{...viewport},pointerId:e.pointerId};$('canvas-area').classList.add('panning');$('board').setPointerCapture(e.pointerId);return;}
  const hit=hitObject(e,p);
  if(tool==='select'){
    if(hit){if(e.shiftKey)setSelection(selection.includes(hit)?selection.filter(id=>id!==hit):[...selection,hit]);else if(!selection.includes(hit))setSelection([hit]);if(!engine.isReadOnly()){stopDemo();gesture={kind:'move',start:p,revision:doc.revision,ids:[...selection],objects:doc.objects.filter(o=>selection.includes(o.id)),pointerId:e.pointerId};}}
    else{if(!e.shiftKey)setSelection([]);gesture={kind:'marquee',start:p,original:[...selection],pointerId:e.pointerId};}
  }else if(writable()){
    stopDemo();
    if(tool==='eraser'){if(hit)act({type:'delete',ids:[hit]});return;}
    if(['text','note','bubble'].includes(tool)){textTarget={point:p,id:null,type:tool};$('text-content').value='';$('text-dialog').showModal();$('text-content').focus();return;}
    gesture={kind:tool==='pen'?'path':'shape',tool,start:p,points:[[p.x,p.y]],revision:doc.revision,pointerId:e.pointerId};
  }
  if(gesture)$('board').setPointerCapture(e.pointerId);
});
$('board').addEventListener('pointermove',e=>{const g=gesture;if(!g||g.pointerId!==e.pointerId)return;const p=worldPoint(e);g.last=p;if(g.kind==='pan'){setViewport({...g.viewport,x:g.viewport.x+e.clientX-g.start.x,y:g.viewport.y+e.clientY-g.start.y});return;}if(g.kind==='path'){const last=g.points.at(-1);if(Math.hypot(p.x-last[0],p.y-last[1])>1/viewport.zoom&&g.points.length<12000)g.points.push([p.x,p.y]);previewShape({type:'path',points:g.points,stroke,fill:'none',strokeWidth:width});}else if(g.kind==='shape')previewShape(shapeFromGesture(g,p,e.shiftKey));else if(g.kind==='move'){const dx=p.x-g.start.x,dy=p.y-g.start.y;$('preview').replaceChildren(...g.objects.map(o=>drawObject(translated(o,dx,dy))));for(const id of g.ids){const element=[...$('objects').children].find(el=>el.dataset.objectId===id);if(element)element.setAttribute('opacity','.25');}}else if(g.kind==='marquee'){$('preview').replaceChildren(svg('rect',{x:Math.min(g.start.x,p.x),y:Math.min(g.start.y,p.y),width:Math.abs(p.x-g.start.x),height:Math.abs(p.y-g.start.y),fill:'#a58cd518',stroke:'#b69cd8','stroke-width':1/viewport.zoom}));}});
$('board').addEventListener('pointerup',e=>{const g=gesture;if(!g||g.pointerId!==e.pointerId)return;const p=worldPoint(e);cancelGesture();if(g.kind==='pan')return;if(g.kind==='marquee'){const x=Math.min(p.x,g.start.x),y=Math.min(p.y,g.start.y),r=Math.max(p.x,g.start.x),b=Math.max(p.y,g.start.y);if(r-x>3||b-y>3)setSelection([...g.original,...doc.objects.filter(o=>{const q=objectBounds(o);return q.x>=x&&q.y>=y&&q.x+q.width<=r&&q.y+q.height<=b;}).map(o=>o.id)]);return;}if(g.revision!==doc.revision){toast('작업 중 보드가 변경되어 드래그를 취소했어요. 다시 선택해주세요.');return;}let result;if(g.kind==='path')result=act({type:'create',object:{type:'path',points:g.points,stroke,fill:'transparent',strokeWidth:width}});else if(g.kind==='shape'){const o=shapeFromGesture(g,p,e.shiftKey);if(Math.abs(o.width)+Math.abs(o.height)>2)result=act({type:'create',object:o});}else if(g.kind==='move'){const dx=round(p.x-g.start.x),dy=round(p.y-g.start.y);if((Math.abs(dx)+Math.abs(dy)>1)&&g.ids.length)act({type:'move',ids:g.ids,dx,dy});}if(result?.createdIds&&tool!=='pen')setSelection(result.createdIds);});
$('board').addEventListener('pointercancel',cancelGesture);$('board').addEventListener('lostpointercapture',()=>{if(gesture)cancelGesture();});
$('board').addEventListener('dblclick',e=>{if(!writable())return;const id=hitObject(e,worldPoint(e)),o=doc.objects.find(o=>o.id===id);if(['text','note','bubble'].includes(o?.type)){textTarget={id,point:{x:o.x,y:o.y},type:o.type};$('text-content').value=o.text;$('text-dialog').showModal();$('text-content').focus();}});
$('board').addEventListener('wheel',e=>{e.preventDefault();const r=$('board').getBoundingClientRect();if(e.shiftKey&&!e.ctrlKey&&!e.metaKey)setViewport({...viewport,x:viewport.x-e.deltaX,y:viewport.y-e.deltaY});else zoomAt(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);},{passive:false});

function updateStyle(changes){if(selection.length&&writable())act({type:'update',ids:selection,changes});}
function selectColor(color,apply=true){stroke=color;$('stroke-color').value=color;$('color-value').textContent=color.toUpperCase();document.querySelectorAll('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.color===color));if(apply)updateStyle({stroke:color});}
for(const color of colors){const button=document.createElement('button');button.className='swatch';button.style.background=color;button.dataset.color=color;button.setAttribute('aria-label',`색상 ${color}`);button.addEventListener('click',()=>selectColor(color));$('palette').append(button);}selectColor(stroke,false);
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>chooseTool(b.dataset.tool)));
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>switchPanel(b.dataset.panel)));
$('stroke-color').addEventListener('input',e=>selectColor(e.target.value,false));$('stroke-color').addEventListener('change',e=>selectColor(e.target.value));
$('stroke-width').addEventListener('input',e=>{width=+e.target.value;$('width-value').textContent=`${width} px`;});$('stroke-width').addEventListener('change',()=>updateStyle({strokeWidth:width}));
$('font-size').addEventListener('input',e=>{fontSize=+e.target.value;$('font-value').textContent=`${fontSize} px`;});$('font-size').addEventListener('change',()=>{const ids=selection.filter(id=>['text','note','bubble'].includes(doc.objects.find(o=>o.id===id)?.type));if(ids.length)act({type:'batch',commands:ids.map(id=>({type:'update',ids:[id],changes:{fontSize,...(doc.objects.find(o=>o.id===id).type==='text'?{width:0,height:0}:{})}}))});});
$('fill-enabled').addEventListener('change',e=>{filled=e.target.checked;updateStyle({fill:filled?fill:'transparent'});});$('fill-color').addEventListener('input',e=>fill=e.target.value);$('fill-color').addEventListener('change',()=>{if(filled)updateStyle({fill});});
$('board-title').addEventListener('change',()=>act({type:'metadata',title:$('board-title').value.trim()||'제목 없는 그림'}));$('author').addEventListener('change',()=>{const name=$('author').value.trim()||'익명';act({type:'metadata',author:name});try{communication?.setNickname(name);}catch(e){handleError(e);}});
$('text-form').addEventListener('submit',e=>{e.preventDefault();const text=$('text-content').value;if(!text.trim()||!textTarget)return;let result;if(textTarget.id)result=act({type:'update',ids:[textTarget.id],changes:{text,...(textTarget.type==='text'?{width:0,height:0}:{})}});else result=act({type:'create',object:{type:textTarget.type||'text',x:textTarget.point.x,y:textTarget.point.y,text,fontSize,stroke,strokeWidth:textTarget.type==='bubble'?2:0,fill:textTarget.type==='text'?'transparent':fill,...(textTarget.type==='text'?{}:{width:250,height:160})}});if(result?.ok){$('text-dialog').close();setSelection(result.createdIds?.length?result.createdIds:[textTarget.id]);chooseTool('select');textTarget=null;}});$('text-cancel').onclick=()=>$('text-dialog').close();
$('undo').onclick=()=>{if(!writable())return;stopDemo();try{check(engine.undo());}catch(e){handleError(e);}};$('redo').onclick=()=>{if(!writable())return;stopDemo();try{check(engine.redo());}catch(e){handleError(e);}};
$('delete-selection').onclick=()=>{if(selection.length)act({type:'delete',ids:[...selection]});};
$('duplicate-selection').onclick=()=>{const commands=doc.objects.filter(o=>selection.includes(o.id)).map(o=>{const copy=translated(o,24,24);delete copy.id;return{type:'create',object:copy};});if(commands.length){const result=act({type:'batch',commands});if(result?.ok)setSelection(result.createdIds);}};
$('zoom-in').onclick=()=>zoomAt(1.2);$('zoom-out').onclick=()=>zoomAt(1/1.2);$('zoom-value').onclick=()=>zoomAt(1/viewport.zoom);$('fit-view').onclick=fitView;
$('help-open').onclick=()=>$('help-dialog').showModal();$('export-open').onclick=()=>$('files-dialog').showModal();
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,[contenteditable]')||document.querySelector('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();space=true;return;}if(e.key==='Escape'){cancelGesture();stopDemo();setSelection([]);return;}const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();if(!writable())return;stopDemo();try{check(e.shiftKey?engine.redo():engine.undo());}catch(err){handleError(err);}return;}if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();downloadProject();return;}if(mod)return;const map={v:'select',b:'pen',r:'rect',o:'ellipse',l:'line',t:'text',e:'eraser',h:'hand',n:'note'};if(map[e.key.toLowerCase()])chooseTool(map[e.key.toLowerCase()]);if((e.key==='Delete'||e.key==='Backspace')&&selection.length){e.preventDefault();act({type:'delete',ids:[...selection]});}const steps={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(steps[e.key]&&selection.length){e.preventDefault();const [x,y]=steps[e.key],step=e.shiftKey?10:1;act({type:'move',ids:selection,dx:x*step,dy:y*step});}});
document.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});window.addEventListener('blur',()=>{space=false;cancelGesture();});

function addActivity({name='board',status='success',message=''}={}){const li=document.createElement('li');if(status==='error')li.className='error';li.append(document.createTextNode(message||name));const time=document.createElement('time');time.textContent=`${new Date().toLocaleTimeString('ko-KR',{hour12:false})} · ${name}`;li.append(time);$('activity-log').prepend(li);while($('activity-log').children.length>35)$('activity-log').lastChild.remove();}
function stopDemo(){if(!demoController)return;demoController.abort();demoController=null;$('stop-agent').disabled=true;$('demo-star').disabled=false;$('demo-garden').disabled=false;engine.execute({type:'agent_pen',down:false},{actor:'agent'});addActivity({name:'demo',message:'움직임을 멈췄어요.'});}
async function demo(kind){if(!writable())return;stopDemo();switchPanel('agent');const controller=new AbortController();demoController=controller;$('stop-agent').disabled=false;$('demo-star').disabled=true;$('demo-garden').disabled=true;const call=async(name,args)=>{controller.signal.throwIfAborted();check(await adapter.call(name,args,{signal:controller.signal}));};const wait=()=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>{controller.signal.removeEventListener('abort',abort);resolve();},110);function abort(){clearTimeout(timer);reject(new DOMException('Stopped','AbortError'));}controller.signal.addEventListener('abort',abort,{once:true});});const r=$('board').getBoundingClientRect(),cx=Math.round((r.width/2-viewport.x)/viewport.zoom),cy=Math.round((r.height/2-viewport.y)/viewport.zoom);try{await call('agent_pen',{down:false,color:kind==='star'?'#a88bc7':'#89ad91',width:3});const points=[];if(kind==='star'){for(let i=0;i<=10;i++){const a=-Math.PI/2+i*Math.PI/5,rad=i%2?55:125;points.push([Math.round(cx+Math.cos(a)*rad),Math.round(cy+Math.sin(a)*rad)]);}}else{for(let i=0;i<=72;i++){const a=i*Math.PI/36,rad=80+45*Math.cos(5*a);points.push([Math.round(cx+rad*Math.cos(a)),Math.round(cy+rad*Math.sin(a))]);}}await call('agent_move',{x:points[0][0],y:points[0][1]});await call('agent_pen',{down:true});for(const [x,y]of points.slice(1)){await wait();await call('agent_move',{x,y});}await call('agent_pen',{down:false});addActivity({name:'demo',message:'그림을 다 그렸어요. 이제 직접 이어 그려보세요.'});}catch(e){if(e.name!=='AbortError')handleError(e);}finally{if(demoController===controller){demoController=null;$('stop-agent').disabled=true;$('demo-star').disabled=false;$('demo-garden').disabled=false;}}}
$('demo-star').onclick=()=>demo('star');$('demo-garden').onclick=()=>demo('garden');$('stop-agent').onclick=stopDemo;
document.querySelectorAll('[data-agent-step]').forEach(b=>b.onclick=async()=>{if(!writable())return;stopDemo();const[dx,dy]=b.dataset.agentStep.split(',').map(Number);try{check(await adapter.call('agent_move',{dx,dy}));}catch(e){handleError(e);}});
$('agent-pen-toggle').onclick=async()=>{if(!writable())return;try{check(await adapter.call('agent_pen',{down:!doc.agent.penDown,color:stroke,width}));}catch(e){handleError(e);}};
$('follow-agent').onclick=()=>{const r=$('board').getBoundingClientRect();setViewport({...viewport,x:r.width/2-doc.agent.x*viewport.zoom,y:r.height/2-doc.agent.y*viewport.zoom});};$('clear-log').onclick=()=>$('activity-log').replaceChildren();

function saveStatus(text,error=false){$('save-status').textContent=text;$('save-status').classList.toggle('error',error);}
function persist(documentToSave=engine.getDocument()){if(!storage||!hasDocument||engine.isReadOnly())return persistQueue;const snapshot=structuredClone(documentToSave);persistQueue=persistQueue.catch(()=>{}).then(async()=>{await storage.save(snapshot);await storage.setLastId(snapshot.id);if(doc.id===snapshot.id&&doc.revision===snapshot.revision)saveStatus('이 기기에 저장됨');}).catch(e=>{saveStatus('자동 저장 실패 · 파일로 저장해주세요',true);throw e;});return persistQueue;}
async function flushSave(){clearTimeout(saveTimer);await persist();}
function beginTransition(){cancelGesture();stopDemo();loading=true;return ++routeVersion;}
function ensureTransition(version,signal){signal?.throwIfAborted();if(version!==routeVersion)throw new DOMException('다른 보드를 여는 작업으로 전환했어요.','AbortError');}
function clearRoute(){history.replaceState(null,'',location.pathname+location.search);committedURL=location.href;}
async function switchDocument(next,{readOnly=false,signal,version=beginTransition(),url='clear',expected}={}){
  try{await flushSave();ensureTransition(version,signal);if(expected&&(doc.id!==expected.id||doc.revision!==expected.revision))throw new Error('보드가 변경되어 전환을 취소했어요. 최신 상태에서 다시 시도해주세요.');check(engine.load(next,{readOnly}));hasDocument=true;selection=[];
    if(url==='clear')clearRoute();else if(url){history.pushState(null,'',url);committedURL=location.href;}else committedURL=location.href;
    render();renderSources();chooseTool('select');requestAnimationFrame(fitView);
    if(readOnly)saveStatus('원본 스냅샷 · 읽기 전용');else{saveStatus('저장 중…');persist().catch(handleError);}
  }finally{if(version===routeVersion)loading=false;}
}
async function openSource(next){const version=beginTransition();try{const url=await shareURL(next);ensureTransition(version);await switchDocument(next,{readOnly:true,version,url});}finally{if(version===routeVersion)loading=false;}}
async function shareBoard({signal}={}){signal?.throwIfAborted();const snapshot=engine.getDocument();const[url,hash]=await Promise.all([shareURL(snapshot),snapshotHash(snapshot)]);signal?.throwIfAborted();return{ok:true,url,hash,revision:snapshot.revision,documentId:snapshot.id};}
async function quoteBoard({url,dx,dy,signal,actor='agent'}={}){
  signal?.throwIfAborted();if(engine.isReadOnly())throw new Error('현재 원본을 먼저 포크한 뒤 다른 그림을 인용해주세요.');
  const version=beginTransition(),target=engine.getDocument();try{const source=await fromURL(url),b=bounds(source.objects),r=$('board').getBoundingClientRect();
    const offsetX=dx??Math.round((r.width/2-viewport.x)/viewport.zoom-b.x-b.width/2),offsetY=dy??Math.round((r.height/2-viewport.y)/viewport.zoom-b.y-b.height/2);
    const command=await prepareQuoteCommand(target,source,{dx:offsetX,dy:offsetY,sourceURL:url});const sourceHash=await snapshotHash(source);ensureTransition(version,signal);
    if(doc.id!==target.id||doc.revision!==target.revision)throw new Error('보드가 변경됐어요. 최신 상태에서 다시 인용해주세요.');
    const result=check(engine.execute(command,{actor}));setSelection(result.createdIds||[]);renderSources();switchPanel('source');onQuoteSaved();return{...result,sourceHash};
  }finally{if(version===routeVersion){loading=false;persist().catch(handleError);}}
}
function onQuoteSaved(){toast('그림을 현재 보드에 인용했어요. 한 번에 되돌릴 수 있어요.');}
async function forkBoard({selectionOnly=false,title,signal}={}){
  signal?.throwIfAborted();const ids=[...selection];if(selectionOnly&&!ids.length)throw new Error('인용할 객체를 먼저 선택해주세요.');
  const version=beginTransition(),source=engine.getDocument();const name=communication?.getNickname()||'나';
  try{const next=await forkDocument(source,{author:name,title:title||(selectionOnly?`${source.title} · 선택 인용`:`${source.title} · 이어 그리기`).slice(0,120),selectionIds:selectionOnly?ids:undefined,sourceURL:location.href});ensureTransition(version,signal);
    if(engine.getDocument().id!==source.id||engine.getDocument().revision!==source.revision)throw new Error('그동안 보드가 변경됐어요. 최신 상태에서 다시 포크해주세요.');
    await switchDocument(next,{version,signal,expected:source});switchPanel('source');toast(selectionOnly?'선택한 그림을 인용한 새 보드를 만들었어요.':'원본을 보관하고 새 보드로 이어갑니다.');return{ok:true,documentId:next.id,sourceHash:next.provenance[0].sourceHash};
  }finally{if(version===routeVersion)loading=false;}
}
async function showShare(){stopDemo();const result=await shareBoard();$('share-url').value=result.url;$('share-detail').textContent=`${result.url.length.toLocaleString()}자 · 원본 식별 ${result.hash.slice(0,12)}${result.url.length>16000?' · 링크가 길어요. 프로젝트 파일로 공유하는 방법도 있어요.':''}`;$('share-dialog').showModal();}
busyButton('share-board',showShare);busyButton('share-tip',showShare);busyButton('fork-board',()=>forkBoard());busyButton('fork-source',async()=>{await forkBoard();switchPanel('draw');chooseTool('bubble');toast('새 보드에 말풍선이나 그림을 더해보세요.');});busyButton('fork-from-panel',()=>forkBoard());busyButton('quote-selection',()=>forkBoard({selectionOnly:true}));
busyButton('copy-link',async()=>{try{await navigator.clipboard.writeText($('share-url').value);toast('공유 링크를 복사했어요.');}catch{$('share-url').focus();$('share-url').select();toast('링크를 선택했어요. Ctrl/⌘ C로 복사해주세요.');}});
busyButton('new-board',async()=>{stopDemo();const author=communication?.getNickname()||'나';await switchDocument(createDocument({title:'제목 없는 그림',author}));switchPanel('draw');setViewport({x:60,y:50,zoom:1});toast('새 보드를 만들었어요.');});
function fileName(){return(doc.title||'grimpan').replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').slice(0,80);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function downloadProject(){download(new Blob([JSON.stringify(engine.getDocument(),null,2)],{type:'application/json'}),`${fileName()}.grimpan.json`);toast('편집 가능한 프로젝트 파일을 저장했어요.');}
$('save-project').onclick=downloadProject;$('download-json').onclick=downloadProject;
function exportSVG(){const b=bounds(),pad=35,out=svg('svg',{xmlns:NS,viewBox:`${b.x-pad} ${b.y-pad} ${b.width+pad*2} ${b.height+pad*2}`,width:Math.ceil(b.width+pad*2),height:Math.ceil(b.height+pad*2)});out.append(svg('rect',{x:b.x-pad,y:b.y-pad,width:b.width+pad*2,height:b.height+pad*2,fill:'#ffffff',stroke:'none'}));doc.objects.forEach(o=>out.append(drawObject(o)));return out;}
$('download-svg').onclick=()=>download(new Blob([new XMLSerializer().serializeToString(exportSVG())],{type:'image/svg+xml'}),`${fileName()}.svg`);
busyButton('download-png',async()=>{const out=exportSVG(),w=+out.getAttribute('width'),h=+out.getAttribute('height'),scale=Math.min(2,4096/w,4096/h,Math.sqrt(12_000_000/(w*h))),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(out)],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('이미지 저장에 실패했어요.');download(blob,`${fileName()}.png`);}finally{URL.revokeObjectURL(url);}});
$('import-project').onclick=()=>$('project-file').click();$('project-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>LIMITS.bytes*1.8)throw new Error('프로젝트 파일은 5 MiB 이하로 가져와주세요.');const parsed=validateDocument(JSON.parse(await file.text()));const verified=await decodeSnapshot(await encodeSnapshot(parsed));$('files-dialog').close();await openSource(verified);toast('프로젝트 원본을 열었어요. 포크해서 수정할 수 있어요.');}catch(e){handleError(e);}finally{$('project-file').value='';}});
async function fromURL(value){let url;try{url=new URL(value,location.href);}catch{throw new Error('공유 링크가 올바르지 않아요.');}if(!url.hash.startsWith('#board='))throw new Error('그림 데이터가 담긴 #board= 링크를 넣어주세요.');return decodeSnapshot(url.hash.slice(7));}
busyButton('open-shared-url',async()=>{const next=await fromURL($('import-url').value.trim());$('files-dialog').close();await openSource(next);toast('공유 원본을 열었어요.');});
busyButton('quote-shared-url',async()=>{const result=await quoteBoard({url:$('import-url').value.trim(),actor:'human'});if(result.ok)$('files-dialog').close();});
async function library(){await flushSave();const boards=await storage.list();const list=$('library-list');list.replaceChildren();if(!boards.length){const p=document.createElement('p');p.className='muted';p.textContent='저장된 보드가 아직 없어요.';list.append(p);}for(const saved of boards){const card=document.createElement('article');card.className='library-card';const preview=document.createElement('button');preview.className='library-preview';preview.setAttribute('aria-label',`${saved.title} 열기`);const b=bounds(saved.objects),image=svg('svg',{viewBox:`${b.x-20} ${b.y-20} ${b.width+40} ${b.height+40}`});saved.objects.slice(0,1000).forEach(o=>image.append(drawObject(o)));preview.append(image);preview.onclick=async()=>{try{$('library-dialog').close();stopDemo();await switchDocument(saved);}catch(e){handleError(e);}};const info=document.createElement('div');info.className='library-info';const title=document.createElement('strong');title.textContent=saved.title;const details=document.createElement('span');details.textContent=`${saved.author} · ${saved.objects.length}개 · ${new Date(saved.updatedAt).toLocaleDateString('ko-KR')}`;info.append(title,details);const remove=document.createElement('button');remove.className='library-delete';remove.title='이 기기의 보드 삭제';remove.setAttribute('aria-label',`${saved.title} 삭제`);const ico=svg('svg');ico.append(svg('use',{href:'#i-trash'}));remove.append(ico);remove.disabled=saved.id===doc.id;remove.onclick=async()=>{try{await storage.remove(saved.id);card.remove();toast('이 기기의 보드를 삭제했어요. 공유 링크는 그대로 열 수 있어요.');}catch(e){handleError(e);}};card.append(preview,info,remove);list.append(card);}$('library-dialog').showModal();}
busyButton('open-library',library);

function starter(){const d=createDocument({title:'함께 그리는 첫 장',author:'나'});const objs=[];const add=o=>objs.push({id:`welcome_${objs.length}`,x:0,y:0,width:0,height:0,stroke:'#6f5c83',fill:'transparent',strokeWidth:0,rotation:0,...o});
  add({type:'text',x:70,y:65,text:'A LITTLE SPACE FOR YOUR IDEAS',fontSize:11,stroke:'#b0a3bf'});
  add({type:'text',x:67,y:100,text:'생각은 나누고,\n그림은 이어 그리고.',fontSize:42,stroke:'#5f526d'});
  add({type:'text',x:70,y:222,text:'작은 낙서 하나에서 시작되는 새로운 대화',fontSize:14,stroke:'#b0a4bc'});
  add({type:'rect',x:65,y:300,width:190,height:142,fill:'#e9e3f8',rotation:-4});
  add({type:'text',x:89,y:328,text:'01  자유롭게 그리기',fontSize:15,stroke:'#8877a4'});add({type:'text',x:89,y:367,text:'선 하나, 생각 하나.\n직접 시작해보세요.',fontSize:13,stroke:'#a799b9'});
  add({type:'rect',x:285,y:318,width:190,height:142,fill:'#e3eadc',rotation:3});
  add({type:'text',x:309,y:346,text:'02  그림 건네기',fontSize:15,stroke:'#839477'});add({type:'text',x:309,y:385,text:'공유 링크에\n지금의 그림을 담아요.',fontSize:13,stroke:'#a0ac96'});
  add({type:'rect',x:505,y:303,width:190,height:142,fill:'#f4e5d5',rotation:-2});
  add({type:'text',x:529,y:331,text:'03  이어 그리기',fontSize:15,stroke:'#aa8f73'});add({type:'text',x:529,y:370,text:'원본을 인용하고\n나의 해석을 더해요.',fontSize:13,stroke:'#bda78f'});
  add({type:'path',points:[[550,108],[570,86],[583,116],[612,117],[590,135],[598,164],[571,147],[548,163],[551,136],[529,118],[550,108]],stroke:'#c0a7db',strokeWidth:2.5});
  add({type:'path',points:[[644,210],[654,224],[670,228],[660,235],[654,250],[648,237],[634,231],[647,222],[644,210]],stroke:'#c3cfb4',strokeWidth:2});
  add({type:'text',x:79,y:490,text:'✳  모든 요소를 선택해서 옮기고 바꿀 수 있어요.',fontSize:11,stroke:'#b2a6c0'});
  d.objects=objs;d.agent={x:730,y:475,heading:225,penDown:false,color:'#a58bd0',width:3};return validateDocument(d);
}
engine.subscribe(event=>{render();if(event.type==='load')renderSources();$('agent-cursor').classList.toggle('busy-indicator',Boolean(demoController));clearTimeout(saveTimer);if(!engine.isReadOnly()&&!loading){saveStatus('저장 중…');saveTimer=setTimeout(()=>persist().catch(handleError),350);}});
async function route(){const version=beginTransition();try{if(location.hash.startsWith('#board=')){const next=await decodeSnapshot(location.hash.slice(7));ensureTransition(version);await switchDocument(next,{readOnly:true,version,url:null});}else{const last=await storage.getLastId();const saved=last?await storage.get(last):null;ensureTransition(version);await switchDocument(saved||starter(),{version});}}catch(e){if(version===routeVersion){toast(`그림을 열지 못했어요: ${e.message}`,true);if(!hasDocument){check(engine.load(starter()));hasDocument=true;render();fitView();}history.replaceState(null,'',committedURL);saveStatus('링크 또는 파일을 확인해주세요',true);}}finally{if(version===routeVersion){loading=false;if(!engine.isReadOnly())persist().catch(handleError);}}}
async function init(){try{localStorage.removeItem('grimpan-author');}catch{}storage=await createStorage();if(storage.degraded)toast(storage.message||'브라우저 저장 공간을 사용할 수 없어요. 프로젝트 파일로 저장해주세요.',true);communication=installCommunication({engine,svg,worldPoint,getViewport:()=>({...viewport}),forkBoard,onError:handleError,onToast:toast,isBusy:()=>loading});story=installStory({engine,svg,drawObject,objectBounds,getSelection:()=>[...selection],getViewport:()=>({...viewport}),setViewport,isBusy:()=>loading,onToast:toast,onError:handleError});adapter=installWebMCP({engine,getSelection:()=>[...selection],setSelection,setViewport,getViewport:()=>({...viewport}),shareBoard,forkBoard,quoteBoard,onActivity:addActivity,isBusy:()=>loading,getNickname:()=>communication.getNickname(),setNickname:name=>communication.setNickname(name)});const native=await adapter.ready;$('webmcp-status').textContent=adapter.supported?`WebMCP 연결됨 · Chrome 네이티브 도구 ${adapter.tools.length}개`:'로컬 도구 준비됨 · WebMCP는 지원 브라우저에서 연결';$('webmcp-status').classList.toggle('connected',adapter.supported);chooseTool('select');await route();window.grimpan=Object.freeze({call:(name,args,options)=>adapter.call(name,args,options),getDocument:()=>engine.getDocument(),getSelection:()=>[...selection],getViewport:()=>({...viewport}),isReadOnly:()=>engine.isReadOnly(),tools:adapter.tools,ready:Promise.resolve(native),version:'1.1.0'});addActivity({name:'ready',message:'보라가 준비됐어요. 이동하거나 데모를 실행해보세요.'});}
window.addEventListener('hashchange',()=>route());window.addEventListener('popstate',()=>{if(!location.hash)route();});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){stopDemo();clearTimeout(saveTimer);persist().catch(()=>{});}});window.addEventListener('pagehide',()=>{stopDemo();clearTimeout(saveTimer);persist().catch(()=>{});});
new ResizeObserver(()=>{if(viewport.zoom)setViewport(viewport);}).observe($('canvas-area'));
init().catch(e=>{saveStatus('시작하지 못했어요',true);handleError(e);console.error(e);});
