// Reading order and visual comparisons are views of the same portable document.
export function installStory({engine,svg,drawObject,objectBounds,getSelection,getViewport,setViewport,isBusy,onToast,onError}){
  const $=id=>document.getElementById(id),make=(tag,className,text)=>{const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e;};
  const button=(text,className,fn)=>{const b=make('button',className,text);b.type='button';b.addEventListener('click',fn);return b;};
  const tab=button('장면','',()=>switchPanel());tab.id='tab-story';tab.dataset.panel='story';tab.setAttribute('role','tab');tab.setAttribute('aria-selected','false');document.querySelector('.panel-tabs').insertBefore(tab,$('tab-source'));
  const panel=make('section','panel-body');panel.id='panel-story';panel.hidden=true;panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby','tab-story');document.querySelector('.side-panel').insertBefore(panel,document.querySelector('.panel-footer'));
  const label=make('div','section-label','ONE PICTURE, MANY MOMENTS'),heading=make('h2',null,'그림을 읽는 순서도\n함께 건네요.');heading.style.whiteSpace='pre-line';
  const intro=make('p','muted','선택한 영역이나 지금 화면을 장면으로 저장하세요. 설명과 함께 순서대로 볼 수 있어요.');
  const form=make('form','story-form'),name=make('input','text-input'),description=make('textarea','social-textarea');name.id='scene-title';name.placeholder='장면 제목';name.maxLength=120;name.setAttribute('aria-label','장면 제목');description.id='scene-description';description.placeholder='이 장면에서 전하고 싶은 이야기';description.maxLength=2000;description.rows=3;description.setAttribute('aria-label','장면 설명');
  const save=button('＋ 지금 화면을 장면으로','button soft full',()=>{});save.id='scene-add';save.type='submit';form.append(name,description,save);
  const list=make('div','story-list');list.id='scene-list';const play=button('▷ 장면 순서대로 보여주기','button primary full',()=>{if(!engine.getDocument().frames?.length)return onToast('먼저 장면을 하나 저장해주세요.');presenting=true;document.body.classList.add('presenting');showFrame(0);});play.id='scene-present';
  panel.append(label,heading,intro,form,list,play);
  const overlay=make('div','story-overlay');overlay.hidden=true;overlay.id='story-overlay';const counter=make('span','story-counter'),title=make('strong'),caption=make('p');const controls=make('div','story-controls');const prev=button('←','',()=>showFrame(activeIndex-1)),next=button('→','',()=>showFrame(activeIndex+1)),end=button('닫기 ×','',close);prev.setAttribute('aria-label','이전 장면');next.setAttribute('aria-label','다음 장면');end.id='scene-close';controls.append(prev,counter,next,end);overlay.append(title,caption,controls);$('canvas-area').append(overlay);
  const compare=make('dialog','compare-dialog');compare.id='compare-dialog';const top=make('div','dialog-top');top.append(make('span','section-label','TWO VERSIONS, ONE CONVERSATION'),button('×','dialog-close',()=>compare.close()));const compareHeading=make('h2',null,'어떻게 이어졌을까요?');const grid=make('div','compare-grid');compare.append(top,compareHeading,grid);document.body.append(compare);
  let activeIndex=-1,activeId=null,presenting=false;
  function switchPanel(){document.querySelectorAll('[data-panel]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.panel==='story')));document.querySelectorAll('.side-panel .panel-body').forEach(p=>p.hidden=p!==panel);}
  function write(command){if(isBusy())throw new Error('보드를 여는 중이에요. 잠시 뒤 다시 시도해주세요.');if(engine.isReadOnly())throw new Error('원본을 포크하면 장면을 추가할 수 있어요.');const r=engine.execute(command,{actor:'human'});if(!r.ok)throw new Error(r.error.message);return r;}
  function selectedBounds(){const objects=engine.getDocument().objects.filter(o=>getSelection().includes(o.id));if(!objects.length){const v=getViewport(),r=$('board').getBoundingClientRect();return{x:-v.x/v.zoom,y:-v.y/v.zoom,width:r.width/v.zoom,height:r.height/v.zoom};}const b=objects.map(objectBounds),x=Math.min(...b.map(p=>p.x)),y=Math.min(...b.map(p=>p.y)),right=Math.max(...b.map(p=>p.x+p.width)),bottom=Math.max(...b.map(p=>p.y+p.height));return{x:x-30,y:y-30,width:Math.max(80,right-x+60),height:Math.max(80,bottom-y+60)};}
  form.addEventListener('submit',e=>{e.preventDefault();try{const n=engine.getDocument().frames?.length||0;write({type:'frame_add',frame:{title:name.value.trim()||`장면 ${n+1}`,description:description.value.trim(),...selectedBounds()}});name.value='';description.value='';onToast('설명과 함께 장면을 저장했어요.');}catch(e){onError(e);}});
  function showFrame(index){const frames=engine.getDocument().frames||[];if(!frames.length){close();return;}activeIndex=((index%frames.length)+frames.length)%frames.length;const frame=frames[activeIndex];activeId=frame.id;overlay.hidden=false;title.textContent=frame.title;caption.textContent=frame.description;caption.hidden=!frame.description;counter.textContent=`${activeIndex+1} / ${frames.length}`;requestAnimationFrame(()=>{const r=$('board').getBoundingClientRect(),zoom=Math.max(.1,Math.min(4,(r.width-70)/frame.width,(r.height-175)/frame.height));setViewport({zoom,x:(r.width-frame.width*zoom)/2-frame.x*zoom,y:(r.height-100-frame.height*zoom)/2-frame.y*zoom});});refreshList();}
  function close(){activeIndex=-1;activeId=null;presenting=false;overlay.hidden=true;document.body.classList.remove('presenting');refreshList();}
  function refreshList(){const document=engine.getDocument(),frames=document.frames||[];list.replaceChildren();if(!frames.length)list.append(make('p','social-empty','첫 장면을 저장하면, 그림을 설명하는 순서가 생겨요.'));frames.forEach((frame,i)=>{const card=make('article',`story-card${activeId===frame.id?' active':''}`),go=button(`${String(i+1).padStart(2,'0')}  ${frame.title}`,'story-go',()=>showFrame(i));const text=make('p',null,frame.description||'설명 없이 저장한 장면');card.append(go,text);if(!engine.isReadOnly()){const remove=button('삭제','text-button',()=>{try{write({type:'frame_delete',id:frame.id});}catch(e){onError(e);}});remove.setAttribute('aria-label',`${frame.title} 장면 삭제`);card.append(remove);}list.append(card);});save.disabled=engine.isReadOnly();name.disabled=engine.isReadOnly();description.disabled=engine.isReadOnly();play.disabled=!frames.length;if(activeId&&!frames.some(f=>f.id===activeId))close();}
  function renderVersion(document,label){const card=make('section','compare-version');card.append(make('h3',null,label),make('p','muted',`${document.title} · ${document.author}`));const objects=document.objects,b=objects.map(objectBounds);const x=b.length?Math.min(...b.map(r=>r.x))-30:0,y=b.length?Math.min(...b.map(r=>r.y))-30:0,right=b.length?Math.max(...b.map(r=>r.x+r.width))+30:800,bottom=b.length?Math.max(...b.map(r=>r.y+r.height))+30:600;const image=svg('svg',{viewBox:`${x} ${y} ${Math.max(80,right-x)} ${Math.max(80,bottom-y)}`,role:'img','aria-label':`${label} 그림`});objects.forEach(o=>image.append(drawObject(o)));card.append(image,make('span','small muted',`${objects.length}개 객체 · ${document.frames?.length||0}개 장면`));return card;}
  function compareWith(original){const current=engine.getDocument();grid.replaceChildren(renderVersion(original,'인용 원본'),renderVersion(current,'지금의 그림'));compare.showModal();}
  const unsubscribe=engine.subscribe(event=>{if(event.type==='load')close();refreshList();});const key=e=>{if(e.target.closest('input,textarea,[contenteditable]'))return;if(e.key==='Escape'&&activeIndex>=0)close();if(presenting&&['ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();showFrame(activeIndex+(e.key==='ArrowRight'?1:-1));}};document.addEventListener('keydown',key,true);refreshList();
  return{compareWith,showFrame,close,refresh:refreshList,dispose(){unsubscribe();document.removeEventListener('keydown',key,true);tab.remove();panel.remove();overlay.remove();compare.remove();}};
}
